nrows = 15
ncols = 10
ncolours = 4
rows = [
    [ 3, -7, 0, 0],
    [ 3, -7, 0, 0],
    [ 1, -9, 0, 0],
    [ -5, 5, 0, 0],
    [-7, -3, 0, 0],

    [-8, -2, 0, 0],
    [4, -2, 0, -4],
    [ 4, -2, 2, 2],
    [ -3, -2, 2, 3],
    [3, 3, 0, -4],

    [ 4, 4, 0, -2],
    [ 5, 4, 0, 1],
    [ -2, -3, 3, -2],
    [1, -3, 3, 3],
    [0, -3, -3, 4]
]
columns = [
    [5, 10, 0, 0],
    [4, 11, 0, 0],
    [-6, 9, 0, 0],
    [-8, 6, 0, 1],
    [7, 6, -2, 0],

    [-3, 5, 5, 2],
    [-3, 4, 1, 7],
    [-3, -3, 3, 6],
    [5, -3, 1, 6],
    [9, -2, 1, 3]
]
