nrows = 15
ncols = 10
ncolours = 4
rows = [ [ -10, 0, 0, 0,], [ -10, 0, 0, 0,], [ -10, 0, 0, 0,], [ -10, 0, 0, 0,], [ -10, 0, 0, 0,], [ -10, 0, 0, 0,], [ 0, -10, 0, 0,], [ -10, 0, 0, 0,], [ -4, -6, 0, 0,], [ 0, 5, 0, -5,], [ 0, -6, 0, -4,], [ 0, 0, -3, -7,], [ 0, 0, 5, -5,], [ 0, 0, -5, -5,], [ 0, 0, -7, -3,],]
columns = [ [ 7, 3, 3, 2,], [ 7, 3, 3, 2,], [ 7, 3, 2, 3,], [ 7, 3, 1, -4,], [ 7, 3, 1, 4,], [ 7, 3, -2, 3,], [ 8, 2, -2, 3,], [ 8, 2, -2, 3,], [ 8, 2, -2, 3,], [ 8, 3, -2, 2,],]
